In [2]:
import numpy as np

In [5]:
array = np.array([25,64,21])
print(array)                   #Result = [25 64 21]

[25 64 21]


In [7]:
array2 = np.array([1,2,3])
print(array2.shape)             #Result = (3,)

(3,)


In [16]:
x =array2.reshape(3,1)
print(x)                       #Result = [[1][2][3]]

[[1]
 [2]
 [3]]


In [18]:
print("Shape: ", x.shape)      #Result = Shape: (3,1)

Shape:  (3, 1)


In [23]:
print("Dimension: ", x.ndim)   #Result = Dimension: 2

Dimension:  2


In [24]:
print("Data Type: ", x.dtype.name)   #Result = Data Type: int32

Data Type:  int32


In [26]:
print("Size: ", x.size)   #Result = Size:  3

Size:  3


In [31]:
print("Type: ", type(x))   #Result = Type:  <class 'numpy.ndarray'>

Type:  <class 'numpy.ndarray'>


In [34]:
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array3)               #Result = [[1,2,3],[4,5,6],[7,8,9]]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
array3.shape                #Result = (3,3)

(3, 3)

In [40]:
zeros = np.zeros((2,2))
print(zeros)                  #Result = [[0. 0.],[0. 0.]]

[[0. 0.]
 [0. 0.]]


In [42]:
ones = np.ones((2,2))
print(ones)                  #Result = [[1. 1.],[1. 1.]]

[[1. 1.]
 [1. 1.]]


In [47]:
np.arange(20,60,8)            #Result = array([20, 28, 36, 44, 52])

array([20, 28, 36, 44, 52])

In [54]:
y = np.linspace(0,2,5)       #Result = [0.  0.5 1.  1.5 2. ]
print(y)

[0.  0.5 1.  1.5 2. ]


In [57]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)                   #Result = [5 7 9]
print(a-b)                   #Result = [-3 -3 -3]
print(a*b)                   #Result = [ 4 10 18]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [58]:
a = np.array([1,2,3])
b = a
c = a

In [60]:
b[0] = 2
print(a,b,c)              #Result = [2 2 3] [2 2 3] [2 2 3]

[2 2 3] [2 2 3] [2 2 3]


In [62]:
d = a.copy()
print(d)                  #Result = [2 2 3]

[2 2 3]


In [64]:
a[0:2]                    #Result = array([2, 2])

array([2, 2])

In [88]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
print(b[:,1])               #Result = [2 6]

[2 6]


In [76]:
print(b[:,-1])               #Result = [4 8]

[4 8]


In [86]:
b = b.ravel()
b                            #Result = array([1, 2, 3, 4, 5, 6, 7, 8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [90]:
b.T                          #Result = array([[1, 5],[2, 6],[3, 7],[4, 8]])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])